### PR TITLE
[SimpleStore] Ensure Update call doesn't erase existing metadata

### PR DESCRIPTION
**Pull request by IfSentient**
In resource.SimpleStore.Update, make a Get call first to get the current metadata (as only the spec is passed), then run the ObjectMetadataOptions on the resulting metadata. Otherwise, the subsequent PUT call in the underlying Client erases the existing non-managed metadata (such as finalizers).

### CODE REVIEW

**Comment by joeblubaugh** [comment]
@cesararmada does this affect your work at all?

**Comment by cesararmada** [comment]
> @cesararmada does this affect your work at all?

Yes, this fixes the bug I was trying to solve.

**Review by radiohead — COMMENTED** [review]
@IfSentient I'm not sure this is the correct approach here. I agree with TODO however – this could work if we'd switch to patching instead of updating.

IMHO we should either:

a) Keep current semantics of `Update` intact and add a new `Patch` (?) method with patch semantics.
b) Rename `Update` to `Patch` (?) and change it to use patch semantics.
C) Keep current semantics of `Update` intact and add a new `Merge` (?) method. `Merge` would work with Get-and-Put semantics.

i.e. the way I see it `Update == PUT`, so the caller must keep track of the client vs. server state themselves but in return they get better performance (i.e. calling `Update` results in a single API call).

In general I would prefer not to rely on get-and-put semantics unless absolutely necessary, because they create a lot of server-side overhead.

**Comment by IfSentient** [comment]
> @IfSentient I'm not sure this is the correct approach here. I agree with TODO however – this could work if we'd switch to patching instead of updating.
> 
> IMHO we should either:
> 
> a) Keep current semantics of `Update` intact and add a new `Patch` (?) method with patch semantics. b) Rename `Update` to `Patch` (?) and change it to use patch semantics. C) Keep current semantics of `Update` intact and add a new `Merge` (?) method. `Merge` would work with Get-and-Put semantics.
> 
> i.e. the way I see it `Update == PUT`, so the caller must keep track of the client vs. server state themselves but in return they get better performance (i.e. calling `Update` results in a single API call).
> 
> In general I would prefer not to rely on get-and-put semantics unless absolutely necessary, because they create a lot of server-side overhead.

@radiohead the big problem with the PUT semantics of Update in SimpleStore is that SImpleStore is designed to only consume the spec object (in order to be "simple"), so the only way to pass along metadata is via get-and-put. This isn't a problem for TypedStore and Store, because they take whole objects in their Update methods.

Also note that get-and-put is done _anyway_ if a ResourceVersion is not present in the UpdateOptions for _any_ Client.Update interaction (via stores or directly), because for CRD's in kubernetes, leaving the RV empty to implicitly use latest doesn't work.

**Comment by radiohead** [comment]
> > @IfSentient I'm not sure this is the correct approach here. I agree with TODO however – this could work if we'd switch to patching instead of updating.
> > IMHO we should either:
> > a) Keep current semantics of `Update` intact and add a new `Patch` (?) method with patch semantics. b) Rename `Update` to `Patch` (?) and change it to use patch semantics. C) Keep current semantics of `Update` intact and add a new `Merge` (?) method. `Merge` would work with Get-and-Put semantics.
> > i.e. the way I see it `Update == PUT`, so the caller must keep track of the client vs. server state themselves but in return they get better performance (i.e. calling `Update` results in a single API call).
> > In general I would prefer not to rely on get-and-put semantics unless absolutely necessary, because they create a lot of server-side overhead.
> 
> @radiohead the big problem with the PUT semantics of Update in SimpleStore is that SImpleStore is designed to only consume the spec object (in order to be "simple"), so the only way to pass along metadata is via get-and-put. This isn't a problem for TypedStore and Store, because they take whole objects in their Update methods.

Fair point – in such case I suggest that we switch to using PATCH instead of PUT.

> Also note that get-and-put is done _anyway_ if a ResourceVersion is not present in the UpdateOptions for _any_ Client.Update interaction (via stores or directly), because for CRD's in kubernetes, leaving the RV empty to implicitly use latest doesn't work.

Yeah and I'm not a big fan of this, but it's a separate topic for discussion.

Let me expand on my reasoning – I tend to think of Kubernetes API as just another storage layer with optional write serialisability. If I were using e.g. SQL I can choose whether I want to force-write some data for efficiency's sake vs. using a transaction for read-compare-update semantics.

Now, Kubernetes API is unfortunately opinionated in that it doesn't provide its API clients with the ability to forcefully apply a specific configuration via the PUT / update verb, i.e. one has to always supply the correct RV. However, in order to emulate the forced write we could use the PATCH verb instead and that'd be my preferred approach here.

**Comment by IfSentient** [comment]
> > > @IfSentient I'm not sure this is the correct approach here. I agree with TODO however – this could work if we'd switch to patching instead of updating.
> > > IMHO we should either:
> > > a) Keep current semantics of `Update` intact and add a new `Patch` (?) method with patch semantics. b) Rename `Update` to `Patch` (?) and change it to use patch semantics. C) Keep current semantics of `Update` intact and add a new `Merge` (?) method. `Merge` would work with Get-and-Put semantics.
> > > i.e. the way I see it `Update == PUT`, so the caller must keep track of the client vs. server state themselves but in return they get better performance (i.e. calling `Update` results in a single API call).
> > > In general I would prefer not to rely on get-and-put semantics unless absolutely necessary, because they create a lot of server-side overhead.
> > 
> > 
> > @radiohead the big problem with the PUT semantics of Update in SimpleStore is that SImpleStore is designed to only consume the spec object (in order to be "simple"), so the only way to pass along metadata is via get-and-put. This isn't a problem for TypedStore and Store, because they take whole objects in their Update methods.
> 
> Fair point – in such case I suggest that we switch to using PATCH instead of PUT.

The only problem I see here (and why I didn't use PATCH originally in the `Update` method) is that we can't do optimistic resource locking with ResourceVersion. I'm OK with saying that `SimpleStore` _doesn't_ do resource locking, and if you want to use that, you have to use `TypedStore` or `Store`, but I just want to make sure this is clear for all folks.

@cesararmada @joeblubaugh IIRC the `resource.WithResourceVersion` option was added for SLO app purposes, is it ok if we make this change to disallow ResourceVersion locking in the `SimpleStore` and refer folks to using `TypedStore` or `Store` for it? `TypedStore` is actually very easy to use with an `operator.Watcher`, as the type you supply it is the same type that comes in from the watcher events.

**Review by radiohead — APPROVED** [review]
Approving this to unblock the bugfix.

**Pull request merged**
